export default {
  GET_SHOP_LIST_REQUEST: "GET_SHOP_LIST_REQUEST",
  GET_SHOP_LIST_RESPONSE: "GET_SHOP_LIST_RESPONSE",

  GET_SHOP_BY_ID_REQUEST: "GET_SHOP_BY_ID_REQUEST",
  GET_SHOP_BY_ID_RESPONSE: "GET_SHOP_BY_ID_RESPONSE",
  GET_SHOP_BY_ID_RESPONSE_CLEAR: "GET_SHOP_BY_ID_RESPONSE_CLEAR",

  POST_SHOP_REQUEST: "POST_SHOP_REQUEST",
  POST_SHOP_RESPONSE: "POST_SHOP_RESPONSE",
  POST_SHOP_RESPONSE_CLEAR: "POST_SHOP_RESPONSE_CLEAR",

  POST_CARD_REQUEST: "POST_CARD_REQUEST",
  POST_CARD_RESPONSE: "POST_CARD_RESPONSE",
  POST_CARD_RESPONSE_CLEAR: "POST_CARD_RESPONSE_CLEAR",

  PUT_SHOP_REQUEST: "PUT_SHOP_REQUEST",
  PUT_SHOP_RESPONSE: "PUT_SHOP_RESPONSE",
  PUT_SHOP_RESPONSE_CLEAR: "PUT_SHOP_RESPONSE_CLEAR",

  DELETE_SHOP_REQUEST: "DELETE_SHOP_REQUEST",
  DELETE_SHOP_RESPONSE: "DELETE_SHOP_RESPONSE",
  DELETE_SHOP_RESPONSE_CLEAR: "DELETE_SHOP_RESPONSE_CLEAR",
};
