export default {
  GET_PRODUCT_LIST_REQUEST: "GET_PRODUCT_LIST_REQUEST",
  GET_PRODUCT_LIST_RESPONSE: "GET_PRODUCT_LIST_RESPONSE",

  GET_PRODUCT_BY_ID_REQUEST: "GET_PRODUCT_BY_ID_REQUEST",
  GET_PRODUCT_BY_ID_RESPONSE: "GET_PRODUCT_BY_ID_RESPONSE",
  GET_PRODUCT_BY_ID_RESPONSE_CLEAR: "GET_PRODUCT_BY_ID_RESPONSE_CLEAR",

  POST_PRODUCT_REQUEST: "POST_PRODUCT_REQUEST",
  POST_PRODUCT_RESPONSE: "POST_PRODUCT_RESPONSE",
  POST_PRODUCT_RESPONSE_CLEAR: "POST_PRODUCT_RESPONSE_CLEAR",

  PUT_PRODUCT_REQUEST: "PUT_PRODUCT_REQUEST",
  PUT_PRODUCT_RESPONSE: "PUT_PRODUCT_RESPONSE",
  PUT_PRODUCT_RESPONSE_CLEAR: "PUT_PRODUCT_RESPONSE_CLEAR",

  DELETE_PRODUCT_REQUEST: "DELETE_PRODUCT_REQUEST",
  DELETE_PRODUCT_RESPONSE: "DELETE_PRODUCT_RESPONSE",
  DELETE_PRODUCT_RESPONSE_CLEAR: "DELETE_PRODUCT_RESPONSE_CLEAR",
};
